part_5/base_app/urls.py
from django.conf.urls import url
from . import views

app_name='base_app'

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r"^user_login/$",views.user_login,name='user_login'),
    
]

part_5/part_5/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from base_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"^$",views.index,name='index'),
    url(r"^base_app",include('base_app.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),

]

part_5/base_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

part_5/base_app/forms.py
from django import forms
from django.contrib.auth.models import User
from base_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

part_5/base_app/views.py
from django.shortcuts import render
# from base_app.models import UserProfileInfo
from base_app.forms import UserForm,UserProfileInfoForm
# Create your views here.

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request,'base_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered=False
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()
            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,'base_app/register.html',{'registered':registered,'user_form':user_form,'profile_form':profile_form})



def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account Not Active')
        else:
            print('Somebay tried to login')
            return HttpResponse('invalid login details supplied')
    else:
        return render(request,'base_app/login.html',{})

part_5/templates/base_app/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Base Html</title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top ">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'base_app:register' %}">Register</a></li>
          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'base_app:user_login' %}">Login</a></li>
          {% endif %}

        </ul>

      </div>

    </nav>
    {% block body_block %}

    {% endblock %}
  </body>
</html>

part_5/templates/base_app/index.html
{% extends 'base_app/basic.html' %}

  {% block body_block %}
    <div class="jumbotron">
      <h1>This is Index Page</h1>
    </div>
  {% endblock %}

part_5/templates/base_app/login.html
{% extends 'base_app/basic.html' %}
{% block body_block %}
<div class="jumbotron">
   <h1>Please Login</h1>
   <form action="{% url 'base_app:user_login' %}" method="post">
     {% csrf_token %}
     <label for="username">Username</label>
     <input type="text" name="username" value="Please enter your Text">

     <label for="password">Password</label>
     <input type="password" name="password">

     <input type="submit" name="" value="Login">

   </form>
</div>
{% endblock %}

part_5/templates/base_app/register.html
{% extends 'base_app/basic.html' %}
{% load static %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron">
        {%  if registered %}
          <h1>Thank you For Registering</h1>
        {% else %}
          <h1>Register Here!</h1>
          <h3>Fill out the Form</h3>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p  }}
            <input type="submit" name="" value="Register">
          </form>
        {%  endif %}
      </div>
  </div>
  {% endblock %}